export default [
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        exports: "writable",
        module: "writable",
        require: "readonly",
        global: "writable",
        URL: "readonly",
        Zotero: "readonly",
        Services: "readonly",
        Components: "readonly",
        ChromeUtils: "readonly",
        Ci: "readonly",
        Cc: "readonly",
        Cu: "readonly",
        dump: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-console": "off",
      "no-undef": "warn",
    },
  },
  {
    ignores: [
      "node_modules/**",
      "build/**",
      "dist/**",
      "*.min.js",
      "coverage/**",
      ".git/**",
      "addon/bootstrap-archive/**",
      "addon/bootstrap-old.js",
      "clean-build/**",
      "plugin-development/**",
      "releases/**",
      "test-*.js",
      "debug-*.js",
    ],
  },
];
