export default [
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        exports: "writable",
        module: "writable",
        require: "readonly",
        global: "writable",
        URL: "readonly",
        Zotero: "readonly",
        Services: "readonly",
        Components: "readonly",
        ChromeUtils: "readonly",
        Ci: "readonly",
        Cc: "readonly",
        Cu: "readonly",
        dump: "readonly",
        // Bootstrap functions
        startup: "readonly",
        shutdown: "readonly",
        install: "readonly",
        uninstall: "readonly",
        // Prefs.js
        pref: "readonly",
        // Browser globals
        window: "readonly",
        document: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        jQuery: "readonly",
        define: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-console": "off",
      "no-undef": "warn",
    },
  },
  {
    ignores: [
      "node_modules/**",
      "build/**",
      "dist/**",
      "*.min.js",
      "**/*.min.js",
      "coverage/**",
      ".git/**",
      "addon/bootstrap-archive/**",
      "addon/bootstrap-old.js",
      "addon/content/lib/**",
      "clean-build/**",
      "plugin-development/**",
      "releases/**",
      "test-*.js",
      "debug-*.js",
      "zotero-source/**",
    ],
  },
];
