// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'addon-description'
  | 'addon-name'
  | 'history-panel-empty'
  | 'history-panel-no-results'
  | 'history-panel-search-placeholder'
  | 'history-panel-title'
  | 'history-toolbar-button'
  | 'menuTools-label'
  | 'menuView-label'
  | 'menuitem-label'
  | 'menupopup-label'
  | 'pref-enable'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
