// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "showToolbarButton": boolean;
      "maxHistoryItems": number;
      "autoSaveHistory": boolean;
      "treeViewType": string;
    };
  }
}
