#!/bin/bash

# Create GitHub Release Script for Zotero Research Navigator

VERSION="v2.6.7"
REPO="sperwe/Zotero-Research-Navigator"
XPI_FILE="/workspace/build/zotero-research-navigator.xpi"
RELEASE_NOTES="/workspace/RELEASE_NOTES_v2.6.7.md"

echo "📦 Creating GitHub Release for $VERSION"
echo "=================================="
echo ""
echo "Steps to create the release:"
echo ""
echo "1. Go to: https://github.com/$REPO/releases/new"
echo ""
echo "2. Choose tag: $VERSION"
echo ""
echo "3. Release title: Zotero Research Navigator $VERSION - Testing Infrastructure & Bug Fixes"
echo ""
echo "4. Copy the release notes from: $RELEASE_NOTES"
echo ""
echo "5. Attach the XPI file: $XPI_FILE"
echo "   File size: $(du -h $XPI_FILE | cut -f1)"
echo ""
echo "6. Check 'Set as the latest release'"
echo ""
echo "7. Click 'Publish release'"
echo ""
echo "✅ Build verification:"
echo "   - Version: $VERSION"
echo "   - XPI exists: $([ -f "$XPI_FILE" ] && echo "YES" || echo "NO")"
echo "   - XPI size: $(ls -lh $XPI_FILE | awk '{print $5}')"
echo "   - Build date: $(date -r $XPI_FILE)"
echo ""
echo "📋 Checklist:"
echo "   [ ] All tests passing"
echo "   [ ] Version numbers consistent"
echo "   [ ] Release notes updated"
echo "   [ ] XPI file tested locally"
echo ""
echo "🚀 Ready to release!"